SEED: 7
DEBUG: False

LOGGING:
  LOSS_FREQ: 10
  EVAL_FREQ: 2

TRAINER:
  LR: 1e-5
  BATCH_SIZE: 8
  EPOCHS: 20
  OPTIMIZER: 'adamw'
  VERBOSE: False

MODEL:
  TYPE: 'resnet'
  SIZE: 18
  PRETRAINED: True
  OUT_CHANNELS: 1
  IN_CHANNELS: 4
  LOSS_TYPE: 'L2'

DATALOADER:
  SPLIT: 'random'  # 'site'
  TRAIN: ['nairobi']
  TEST: ['lagos']
  NUM_WORKER: 8
  SHUFFLE: True
  SPECTRAL_BANDS: ['Red', 'Green', 'Blue', 'NIR']
  SITES: ['nairobi', 'lagos', 'buenosaires']

AUGMENTATION:
  RANDOM_FLIP: True
  RANDOM_ROTATE: True
  COLOR_SHIFT: False
  GAMMA_CORRECTION: False
  RESIZE: False