_BASE_: "base.yaml"

MODEL:
  OUTPUT_ACTIVATION: 'Sigmoid'

TRAINER:
  LR: 1e-4
  BATCH_SIZE: 8
  EPOCHS: 500

DATALOADER:
  LABEL: 'heat'
  SPLIT: 'random'  # random/site
  FOLD: 1
  SITES: ['nairobi', 'lagos', 'buenosaires']
